run:
  mode: 'train'
  device: 'gpu'
transforms: none
dataset:
  class_name: "nuclei_dataset"
  input_size: 224
  data_dir: "/home/gmahalingam/My.Explorations/datasets/data-science-bowl-2018/data"
  training:
    params:
      data_dir: "/home/gmahalingam/My.Explorations/datasets/data-science-bowl-2018/data"
  validation:
    params:
      data_dir: "/home/gmahalingam/My.Explorations/datasets/data-science-bowl-2018/data"
  number_classes: 2
data_loader:
  train: 
    batch_size: 8
    shuffle: true
    num_workers: 8
    pin_memory: true
  validation: 
    batch_size: 8
    shuffle: false
    num_workers: 8
    pin_memory: true
  test:
    batch_size: 8
    shuffle: false
    num_workers: 4
    pin_memory: false
training:
  optimizer:
    name: 'Adam'
    params:
      lr: 0.0001
  criterion:
    name: "DiceLoss"
    params: {}
  scheduler:
    factor: 0.5
    patience: 10
  epochs: 100
model:
  save_dir: '/home/gmahalingam/My.Explorations/unets/saved_models/nuclei2018_uctransnet'
  load_weights: false
  name: "UCTransNet"
  params: 
    n_channels: 3
    n_classes: 2
# preprocess: